spring:
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: luciferabhinavdevil666@gmail.com
    password: jjhk hjum mjrg tngk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 8080

logging:
  level:
    com:
      rjAbhi:
        journalApp: TRACE

weather:
  api:
    key: 5c2b66013088cdf4be36dcf553ca2bae
    url: https://api.weather.com/v3/weather/forecast?latitude={latitude}&longitude={longitude}&apiKey={apiKey}
